name: appcraft_utils_flutter
description: Lightweight Dart utilities and Flutter-friendly extensions for forms, validations, mappers, models, exceptions, notifiers and localization.
version: 0.1.0
repository: https://github.com/AppCraftTeam/appcraft-utils-flutter
homepage: https://github.com/AppCraftTeam/appcraft-utils-flutter
issue_tracker: https://github.com/AppCraftTeam/appcraft-utils-flutter/issues

topics:
  - dart
  - flutter
  - utils
  - validation
  - extensions

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
